---
title: "Tidying Data"
author: "Peter Menzies"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

Read in wb_indiciators.csv file, specify `na = c("..", "")`

```{r}
wb_indicators <- read_csv(file = here("data", "wb_indicators.csv"), na = c("..", ""))
```

## Reshape to make year a single variable

`pivot_longer` to make years a single comlumn

```{r}
wb_indicators_long <- wb_indicators %>% 
  pivot_longer(cols = '2001 [YR2001]':'2020 [YR2020]',
               names_to = "year",
               values_to = "indicator_value")
```

## Clean up year column

```{r}
wb_indicators_sep <- wb_indicators_long %>% 
  separate(col = year, into = c("year", "year_chr"), sep = " ") %>% 
  select(-c(year_chr, 'Country Code', 'Series Code'))
  
```

## Practice: create a tibble 

```{r}
df <- tribble(
  ~name, ~A, ~B, ~C,
  "teddy", 4, 5, 6,
  "khora", 9, 10, 11
)

tidy_df <- df %>% pivot_longer(col = A:C, names_to = "dog_food", values_to = "value")

# undo our previous pivoting:

wide_df <- tidy_df %>% 
  pivot_wider(names_from = dog_food, values_from = value)
```

## Pivot wider for indicator df

```{r}
wb_data_tidy <- wb_indicators_sep %>% 
  drop_na('Series Name') %>% 
  pivot_wider(names_from = 'Series Name', values_from = indicator_value)

names(wb_data_tidy) <- c("country", "year", "access_clean_fuels", "access_electricity", "co2_emissions", "fossil_fuel_cons", "water_stress")

wb_data_tidy <- wb_data_tidy %>% 
  rename(country_name = country,
         electricity = access_electricity)
```


